name: Build tagged release

on:
  push:
    tags:
      - 'v*'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.12

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.22.0

      - name: Install Packages
        run: pnpm install

      - name: Release
        run: npm run release
